[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 4000
  framework = "vite"