#!/bin/bash

echo "🚀 Setting up Blogger CMS Environment..."
echo "Blog ID: 1722387930275850186"
echo ""

# Create .env file
cat > .env << EOF
# Blogger Configuration
REACT_APP_BLOGGER_ID=1722387930275850186

# Get your Blog ID from:
# 1. Go to Blogger Dashboard
# 2. Settings > Basic > Blog ID
# 3. Or check URL when editing your blog

# This file was auto-generated by setup
# Your Blog ID: 1722387930275850186
EOF

echo "✅ .env file created successfully!"
echo "📝 Content:"
cat .env
echo ""
echo "🎯 Setup complete! You can now:"
echo "   1. Restart your development server"
echo "   2. Post content to Blogger with labels"
echo "   3. Test the integration"
echo ""
echo "🧪 Test your Blog ID:"
echo "   https://www.blogger.com/feeds/1722387930275850186/posts/default?alt=rss"
